global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django.rules"

scrape_configs:
  - job_name: 'django'

    static_configs:
      - targets:
          - go:8000
          - ${ALLOWED_HOST}:80
          - ${ALLOWED_HOST}:443
