FROM nginxproxy/nginx-proxy:1.5

#COPY default_location /etc/nginx/vhost.d/default_location
#COPY default.conf /etc/nginx/conf.d/default.conf
COPY add_settings.conf /etc/nginx/conf.d/add_settings.conf